### ISSUE TITLE
5.0.0

### ISSUE THREAD

**Issue by mattdesl** [mattdesl/budo#43]
Budo is growing into a more general-purpose tool than it was when it first started, so I'm looking to create a better UX. Some planned changes:

* [x] add `--open` option which launches the browser; no need for `opnr` anymore
* [x] use auto-portfinding in both CLI and API
* [x] use auto-portfinding for live reload server #34
* [x] include a `--no-portfind` or `{ portfind: false }` option to disable it
* [x] include API aliases for dash-case names like browserify API does
* [x] force all browserify options to be after a full stop `--` to fix #30
* [x] explore proxying / pushstate options #45 #41 
* [x] errorify by default ?

**Comment by mattdesl** [comment]
see the [next](https://github.com/mattdesl/budo/tree/next) branch for 5.0 pre release
